"""create Table SourceCode

Revision ID: 330c1f2d0082
Revises: 658dc4618ebd
Create Date: 2023-03-01 19:19:20.216948

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '330c1f2d0082'
down_revision = '658dc4618ebd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plang_source_code',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('path', sa.String(), nullable=True),
    sa.Column('pathList', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('subset_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['subset_id'], ['plang_subset.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plang_source_code_id'), 'plang_source_code', ['id'], unique=False)
    op.create_index(op.f('ix_plang_source_code_name'), 'plang_source_code', ['name'], unique=False)
    op.create_index(op.f('ix_plang_source_code_type'), 'plang_source_code', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_plang_source_code_type'), table_name='plang_source_code')
    op.drop_index(op.f('ix_plang_source_code_name'), table_name='plang_source_code')
    op.drop_index(op.f('ix_plang_source_code_id'), table_name='plang_source_code')
    op.drop_table('plang_source_code')
    # ### end Alembic commands ###
