"""Initial

Revision ID: 3a8ebeb3cc3c
Revises: 6f53b2968c45
Create Date: 2023-02-20 01:56:12.611490

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '3a8ebeb3cc3c'
down_revision = '6f53b2968c45'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
