"""PLang->AssemblerStmt -> Novos Campos

Revision ID: 658dc4618ebd
Revises: 7e13257087ad
Create Date: 2023-03-01 16:17:12.005983

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '658dc4618ebd'
down_revision = '7e13257087ad'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plang_assembler_stmt', sa.Column('type', sa.String(), nullable=True))
    op.add_column('plang_assembler_stmt', sa.Column('cc', sa.String(), nullable=True))
    op.add_column('plang_assembler_stmt', sa.Column('pf_ipq', sa.String(), nullable=True))
    op.alter_column('plang_assembler_stmt', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index('ix_plang_assembler_stmt_name', table_name='plang_assembler_stmt')
    op.create_index(op.f('ix_plang_assembler_stmt_name'), 'plang_assembler_stmt', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_plang_assembler_stmt_name'), table_name='plang_assembler_stmt')
    op.create_index('ix_plang_assembler_stmt_name', 'plang_assembler_stmt', ['name'], unique=False)
    op.alter_column('plang_assembler_stmt', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('plang_assembler_stmt', 'pf_ipq')
    op.drop_column('plang_assembler_stmt', 'cc')
    op.drop_column('plang_assembler_stmt', 'type')
    # ### end Alembic commands ###
