"""PLang->Subset,AssemblerStmt

Revision ID: 7e13257087ad
Revises: 81d92a66c71d
Create Date: 2023-03-01 16:06:52.300449

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '7e13257087ad'
down_revision = '81d92a66c71d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plang_assembler_stmt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plang_assembler_stmt_id'), 'plang_assembler_stmt', ['id'], unique=False)
    op.create_index(op.f('ix_plang_assembler_stmt_name'), 'plang_assembler_stmt', ['name'], unique=False)
    op.create_table('plang_subset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['plang_subset.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plang_subset_id'), 'plang_subset', ['id'], unique=False)
    op.create_index(op.f('ix_plang_subset_name'), 'plang_subset', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_plang_subset_name'), table_name='plang_subset')
    op.drop_index(op.f('ix_plang_subset_id'), table_name='plang_subset')
    op.drop_table('plang_subset')
    op.drop_index(op.f('ix_plang_assembler_stmt_name'), table_name='plang_assembler_stmt')
    op.drop_index(op.f('ix_plang_assembler_stmt_id'), table_name='plang_assembler_stmt')
    op.drop_table('plang_assembler_stmt')
    # ### end Alembic commands ###
