"""Inclusao Category

Revision ID: 81d92a66c71d
Revises: c1a24d014f1e
Create Date: 2023-02-20 23:35:43.871648

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '81d92a66c71d'
down_revision = 'c1a24d014f1e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fin_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['fin_category.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fin_category_id'), 'fin_category', ['id'], unique=False)
    op.create_index(op.f('ix_fin_category_name'), 'fin_category', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fin_category_name'), table_name='fin_category')
    op.drop_index(op.f('ix_fin_category_id'), table_name='fin_category')
    op.drop_table('fin_category')
    # ### end Alembic commands ###
