"""Retirando Category

Revision ID: b6cb84c66ea1
Revises: 330c1f2d0082
Create Date: 2023-04-15 23:19:42.633978

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = 'b6cb84c66ea1'
down_revision = '330c1f2d0082'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_fin_category_id', table_name='fin_category')
    op.drop_index('ix_fin_category_name', table_name='fin_category')
    op.drop_table('fin_category')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fin_category',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('parent_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], name='fin_category_owner_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['fin_category.id'], name='fin_category_parent_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='fin_category_pkey')
    )
    op.create_index('ix_fin_category_name', 'fin_category', ['name'], unique=False)
    op.create_index('ix_fin_category_id', 'fin_category', ['id'], unique=False)
    # ### end Alembic commands ###
