"""Initial

Revision ID: c1a24d014f1e
Revises: 3a8ebeb3cc3c
Create Date: 2023-02-20 21:09:34.281121

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = 'c1a24d014f1e'
down_revision = '3a8ebeb3cc3c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fin_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fin_account_id'), 'fin_account', ['id'], unique=False)
    op.create_index(op.f('ix_fin_account_name'), 'fin_account', ['name'], unique=False)
    op.drop_index('ix_account_id', table_name='account')
    op.drop_index('ix_account_name', table_name='account')
    op.drop_table('account')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], name='account_owner_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='account_pkey')
    )
    op.create_index('ix_account_name', 'account', ['name'], unique=False)
    op.create_index('ix_account_id', 'account', ['id'], unique=False)
    op.drop_index(op.f('ix_fin_account_name'), table_name='fin_account')
    op.drop_index(op.f('ix_fin_account_id'), table_name='fin_account')
    op.drop_table('fin_account')
    # ### end Alembic commands ###
